[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 200
runOnSave = true
headless = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501
